
--1. ORDER WITH THE HIGHEST QUANTITY ORDERED--

SELECT TOP 10
    OrderNumber,
    ProductCode,
    QuantityOrdered,
    Sales
FROM OrderDetails
ORDER BY QuantityOrdered DESC;


--2. TOP 10 SALES BY ORDER NUMBER--

SELECT TOP 10
    OrderNumber,
    SUM(Sales) AS TotalSales
FROM OrderDetails
GROUP BY OrderNumber
ORDER BY TotalSales DESC;



--3. PRODUCT WITH THE HIGHEST ORDER VOLUME--


SELECT TOP 10
    ProductCode,
    SUM(QuantityOrdered) AS TotalQuantity
FROM OrderDetails
GROUP BY ProductCode
ORDER BY TotalQuantity DESC;



--4. CUSTOMER WITH THE HIGHEST NUMBER OF ORDERS--


SELECT TOP 10
    c.CustomerName,
    COUNT(o.OrderNumber) AS TotalOrders
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerName
ORDER BY TotalOrders DESC;



--5. TOP 10 STATES BY REVENUE GENERATED--


SELECT TOP 10
    c.State,
    SUM(od.Sales) AS TotalRevenue
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
    ON o.OrderNumber = od.OrderNumber
WHERE c.State IS NOT NULL
GROUP BY c.State
ORDER BY TotalRevenue DESC;




--6. TOTAL REVENUE GENERATED BY DEAL SIZE--


SELECT
    DealSize,
    SUM(Sales) AS TotalRevenue
FROM OrderDetails
GROUP BY DealSize
ORDER BY TotalRevenue DESC;



--7. TOP PRODUCT LINES BY REVENUE GENERATED--


SELECT
    p.ProductLine,
    SUM(od.Sales) AS TotalRevenue
FROM Products p
JOIN OrderDetails od
    ON p.ProductCode = od.ProductCode
GROUP BY p.ProductLine
ORDER BY TotalRevenue DESC;



--8. AVERAGE ORDER VALUE--


SELECT AVG(OrderTotal) AS AvgOrderValue
FROM (
    SELECT SUM(Sales) AS OrderTotal
    FROM OrderDetails
    GROUP BY OrderNumber
) t;


--9. CUSTOMERS WITH SALES ABOVE AVERAGE--


WITH CustomerSales AS
(
    SELECT
        c.CustomerName,
        SUM(od.Sales) AS TotalSales
    FROM Customers c
    JOIN Orders o
        ON c.CustomerID = o.CustomerID
    JOIN OrderDetails od
        ON o.OrderNumber = od.OrderNumber
    GROUP BY c.CustomerName
)

SELECT
    CustomerName,
    TotalSales
FROM CustomerSales
WHERE TotalSales >
(
    SELECT AVG(TotalSales)
    FROM CustomerSales
)
ORDER BY TotalSales DESC;



--10. MONTHLY REVENUE TREND--


SELECT
    YEAR_ID,
    MONTH_ID,
    SUM(od.Sales) AS MonthlyRevenue
FROM Orders o
JOIN OrderDetails od
    ON o.OrderNumber = od.OrderNumber
GROUP BY YEAR_ID, MONTH_ID
ORDER BY YEAR_ID, MONTH_ID;



--11. TOP 5 COUNTRIES BY SALES--


SELECT TOP 10
    c.Country,
    SUM(od.Sales) AS TotalRevenue
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
    ON o.OrderNumber = od.OrderNumber
GROUP BY c.Country
ORDER BY TotalRevenue DESC;



--12. TOTAL SALES BY PRODUCT LINE--

SELECT
    p.ProductLine,
    SUM(od.Sales) AS TotalSales
FROM Products p
JOIN OrderDetails od
    ON p.ProductCode = od.ProductCode
GROUP BY p.ProductLine
ORDER BY TotalSales DESC;



--13. PRODUCTS WITH MSRP GREATER THAN 100--


SELECT
    ProductCode,
    ProductLine,
    MSRP
FROM Products
WHERE MSRP > 100
ORDER BY MSRP DESC;



--14. CUSTOMERS WITH MORE THAN 5 ORDERS--


SELECT
    c.CustomerName,
    COUNT(o.OrderNumber) AS TotalOrders
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerName
HAVING COUNT(o.OrderNumber) > 5
ORDER BY TotalOrders DESC;



--15. CUSTOMERS WITH THEIR ORDERS--


SELECT
    c.CustomerID,
    c.CustomerName,
    o.OrderNumber,
    o.OrderDate,
    o.Status
FROM Customers c
INNER JOIN Orders o
    ON c.CustomerID = o.CustomerID
ORDER BY o.OrderDate;



--16. PRODUCTS WITH SALES DETAILS--

SELECT
    p.ProductCode,
    p.ProductLine,
    od.OrderNumber,
    od.QuantityOrdered,
    od.Sales
FROM Products p
INNER JOIN OrderDetails od
    ON p.ProductCode = od.ProductCode
ORDER BY od.Sales DESC;



--17. ALL CUSTOMERS INCLUDING THOSE WITHOUT ORDERS--


SELECT
    c.CustomerID,
    c.CustomerName,
    o.OrderNumber,
    o.Status
FROM Customers c
LEFT JOIN Orders o
    ON c.CustomerID = o.CustomerID
ORDER BY c.CustomerName;



--18. PRODUCTS WITHOUT SALES--


SELECT
    p.ProductCode,
    p.ProductLine
FROM Products p
LEFT JOIN OrderDetails od
    ON p.ProductCode = od.ProductCode
WHERE od.ProductCode IS NULL
ORDER BY p.ProductCode;



--19. ALL ORDERS INCLUDING MISSING CUSTOMER RECORDS--

SELECT
    c.CustomerName,
    o.OrderNumber,
    o.OrderDate,
    o.Status
FROM Customers c
RIGHT JOIN Orders o
    ON c.CustomerID = o.CustomerID
ORDER BY o.OrderDate;



--20. CUSTOMERS WITH ABOVE-AVERAGE SALES--

SELECT
    CustomerName,
    TotalSales
FROM
(
    SELECT
        c.CustomerName,
        SUM(od.Sales) AS TotalSales
    FROM Customers c
    JOIN Orders o
        ON c.CustomerID = o.CustomerID
    JOIN OrderDetails od
        ON o.OrderNumber = od.OrderNumber
    GROUP BY c.CustomerName
) CustomerSales
WHERE TotalSales >
(
    SELECT AVG(TotalSales)
    FROM
    (
        SELECT
            SUM(od.Sales) AS TotalSales
        FROM Customers c
        JOIN Orders o
            ON c.CustomerID = o.CustomerID
        JOIN OrderDetails od
            ON o.OrderNumber = od.OrderNumber
        GROUP BY c.CustomerID
    ) AvgSales
)
ORDER BY TotalSales DESC;



--21. PRODUCTS WITH SALES HIGHER THAN AVERAGE--

SELECT
    ProductCode,
    Sales
FROM OrderDetails
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM OrderDetails
)
ORDER BY Sales DESC;



--22. ROW NUMBER FOR ORDERS BY SALES VALUE--

SELECT
    OrderNumber,
    Sales,
    ROW_NUMBER() OVER (
        ORDER BY Sales DESC
    ) AS RowNum
FROM OrderDetails;



--23. CUSTOMERS RANK BY TOTAL REVENUE--


SELECT
    c.CustomerName,
    SUM(od.Sales) AS TotalRevenue,

    RANK() OVER (
        ORDER BY SUM(od.Sales) DESC
    ) AS RevenueRank

FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
    ON o.OrderNumber = od.OrderNumber

GROUP BY
    c.CustomerName;



--24. TOP PRODUCTS WITHIN EACH PRODUCT LINE--


SELECT
    ProductLine,
    ProductCode,
    TotalRevenue,
    ROW_NUMBER() OVER
    (
        PARTITION BY ProductLine
        ORDER BY TotalRevenue DESC
    ) AS ProductRank
FROM
(
    SELECT
        p.ProductLine,
        p.ProductCode,
        SUM(od.Sales) AS TotalRevenue
    FROM Products p
    JOIN OrderDetails od
        ON p.ProductCode = od.ProductCode
    GROUP BY
        p.ProductLine,
        p.ProductCode
) ProductSales;


--25. RANK PRODUCTS BY TOTAL QUANTITY SOLD--


SELECT
    ProductCode,
    SUM(QuantityOrdered) AS TotalQuantity,

    RANK() OVER
    (
        ORDER BY SUM(QuantityOrdered) DESC
    ) AS QuantityRank

FROM OrderDetails
GROUP BY ProductCode;



--26. LATEST ORDERS PER CUSTOMER--


SELECT
    CustomerID,
    CustomerName,
    OrderNumber,
    OrderDate
FROM
(
    SELECT
        c.CustomerID,
        c.CustomerName,
        o.OrderNumber,
        o.OrderDate,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.CustomerID
            ORDER BY o.OrderDate DESC
        ) AS rn

    FROM Customers c
    JOIN Orders o
        ON c.CustomerID = o.CustomerID
) LatestOrders
WHERE rn = 1;



--27. CUSTOMERS WITH MORE THAN 5 ORDERS--


SELECT
    CustomerName,
    TotalOrders
FROM
(
    SELECT
        c.CustomerName,
        COUNT(o.OrderNumber) AS TotalOrders
    FROM Customers c
    JOIN Orders o
        ON c.CustomerID = o.CustomerID
    GROUP BY c.CustomerName
) CustomerOrders
WHERE TotalOrders > 5
ORDER BY TotalOrders DESC;



--28. RUNNING TOTAL OF MONTHLY SALES--


SELECT
    YEAR_ID,
    MONTH_ID,
    MonthlySales,

    SUM(MonthlySales) OVER
    (
        ORDER BY YEAR_ID, MONTH_ID
    ) AS RunningTotal

FROM
(
    SELECT
        o.YEAR_ID,
        o.MONTH_ID,
        SUM(od.Sales) AS MonthlySales
    FROM Orders o
    JOIN OrderDetails od
        ON o.OrderNumber = od.OrderNumber
    GROUP BY
        o.YEAR_ID,
        o.MONTH_ID
) MonthlyRevenue;


--29. TOP 10 PRODUCTS BY REVENUE--

SELECT TOP 10
    p.ProductCode,
    p.ProductLine,
    SUM(od.Sales) AS TotalRevenue,
    SUM(od.QuantityOrdered) AS UnitsSold,
    COUNT(DISTINCT o.OrderNumber) AS OrderCount
FROM Products p
INNER JOIN OrderDetails od
    ON od.ProductCode = p.ProductCode
INNER JOIN Orders o
    ON o.OrderNumber = od.OrderNumber
GROUP BY
    p.ProductCode,
    p.ProductLine
ORDER BY TotalRevenue DESC;


--30. TOP 10 PERFORMING CUSTOMERS--

SELECT TOP 10
    c.CustomerID,
    c.CustomerName,
    c.Country,
    SUM(od.Sales) AS LifetimeRevenue,
    COUNT(DISTINCT o.OrderNumber) AS TotalOrders
FROM Customers c
JOIN Orders o ON o.CustomerID = c.CustomerID
JOIN OrderDetails od ON od.OrderNumber = o.OrderNumber
GROUP BY c.CustomerID, c.CustomerName, c.Country
ORDER BY LifetimeRevenue DESC;


--31. CUSTOMERS WITH ABOVE AVERAGE SPENDING VALUE--

WITH CustomerSales AS
(
    SELECT
        c.CustomerID,
        c.CustomerName,
        SUM(od.Sales) AS TotalSpent
    FROM Customers c
    INNER JOIN Orders o
        ON o.CustomerID = c.CustomerID
    INNER JOIN OrderDetails od
        ON od.OrderNumber = o.OrderNumber
    GROUP BY
        c.CustomerID,
        c.CustomerName
)

SELECT
    CustomerName,
    TotalSpent
FROM CustomerSales
WHERE TotalSpent >
(
    SELECT AVG(TotalSpent)
    FROM CustomerSales
)
ORDER BY TotalSpent DESC;



--32. TOP PRODUCT LINE BY REVENUE--

SELECT
    p.ProductLine,
    SUM(od.Sales) AS TotalRevenue,
    SUM(od.QuantityOrdered) AS UnitsSold
FROM Products p
INNER JOIN OrderDetails od
    ON od.ProductCode = p.ProductCode
GROUP BY p.ProductLine
ORDER BY TotalRevenue DESC;


--33. MONTHLY REVENUE TREND WITH YEAR ON YEAR GROWTH--


WITH MonthlySales AS (
    SELECT
        o.YEAR_ID,
        o.MONTH_ID,
        SUM(od.Sales) AS Revenue
    FROM Orders o
    JOIN OrderDetails od ON od.OrderNumber = o.OrderNumber
    GROUP BY o.YEAR_ID, o.MONTH_ID
)
SELECT
    YEAR_ID,
    MONTH_ID,
    Revenue,
    LAG(Revenue, 12) OVER (ORDER BY YEAR_ID, MONTH_ID) AS RevenueLY,
    ROUND(
        100.0 * (Revenue - LAG(Revenue, 12) OVER (ORDER BY YEAR_ID, MONTH_ID)) 
        / NULLIF(LAG(Revenue, 12) OVER (ORDER BY YEAR_ID, MONTH_ID), 0), 2
    ) AS YoY_GrowthPct,
    SUM(Revenue) OVER (PARTITION BY YEAR_ID ORDER BY MONTH_ID 
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS YTD_Revenue
FROM MonthlySales
ORDER BY YEAR_ID, MONTH_ID;



--34. MONTHLY REVENUE TREND--

SELECT
    o.YEAR_ID AS SalesYear,
    o.MONTH_ID AS SalesMonth,
    SUM(od.Sales) AS MonthlyRevenue
FROM Orders o
INNER JOIN OrderDetails od
    ON od.OrderNumber = o.OrderNumber
GROUP BY
    o.YEAR_ID,
    o.MONTH_ID
ORDER BY
    SalesYear,
    SalesMonth;


--35. CUSTOMERS PURCHASE FREQUENCY--

SELECT
    c.CustomerName,
    COUNT(DISTINCT o.OrderNumber) AS NumberOfOrders,
    SUM(od.Sales) AS TotalSpent
FROM Customers c
INNER JOIN Orders o
    ON o.CustomerID = c.CustomerID
INNER JOIN OrderDetails od
    ON od.OrderNumber = o.OrderNumber
GROUP BY
    c.CustomerID,
    c.CustomerName
ORDER BY NumberOfOrders DESC;


--36. REVENUE GENERATED BY DEAL SIZE--

SELECT
    od.DealSize,
    COUNT(*) AS TotalOrders,
    SUM(od.Sales) AS TotalRevenue,
    AVG(od.Sales) AS AverageRevenue
FROM OrderDetails od
GROUP BY od.DealSize
ORDER BY TotalRevenue DESC;


--37. TOP CUSTOMERS PER COUNTRY--

WITH CustomerRevenue AS
(
    SELECT
        c.Country,
        c.CustomerName,
        SUM(od.Sales) AS TotalSpent,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.Country
            ORDER BY SUM(od.Sales) DESC
        ) AS rn

    FROM Customers c
    INNER JOIN Orders o
        ON o.CustomerID = c.CustomerID
    INNER JOIN OrderDetails od
        ON od.OrderNumber = o.OrderNumber
         GROUP BY
        c.Country,
        c.CustomerName
)

SELECT
    Country,
    CustomerName,
    TotalSpent
FROM CustomerRevenue
WHERE rn <= 3
ORDER BY
    Country,
    TotalSpent DESC;


--38. HIGHEST VALUE ORDER--

SELECT TOP 10
    od.OrderNumber,
    SUM(od.Sales) AS TotalRevenue
FROM OrderDetails od
GROUP BY od.OrderNumber
ORDER BY TotalRevenue DESC;


--39. BEST SALES QUARTER--

SELECT
    o.QTR_ID,
    SUM(od.Sales) AS TotalRevenue
FROM Orders o
INNER JOIN OrderDetails od
    ON od.OrderNumber = o.OrderNumber
GROUP BY o.QTR_ID
ORDER BY TotalRevenue DESC;


--40. ORDER STATUS ANALYSIS--

SELECT
    o.Status,
    COUNT(DISTINCT o.OrderNumber) AS TotalOrders,
    SUM(od.Sales) AS RevenueGenerated
FROM Orders AS o
INNER JOIN OrderDetails AS od
    ON od.OrderNumber = o.OrderNumber
GROUP BY o.Status
ORDER BY RevenueGenerated DESC;
